/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.service.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {
    public static void main(String[] args) {

        System.out.println("Running Train Booking System");

        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        } catch (IOException ex) {
            System.out.println("There is something wrong");
            return;
        }

        while (option != 7) {
            System.out.println("Choose options given below");
            System.out.println("1. Sign up");
            System.out.println("2. Log in");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit the App");
            option = sc.nextInt();
            Train trainsSelectedForBooking = new Train();

            switch (option) {
                case 1 -> {
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = sc.next();

                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = sc.next();

                    User userToSignUp = new User(nameToSignUp, UUID.randomUUID().toString(), passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),
                            new ArrayList<>());

                    userBookingService.signUp(userToSignUp);
                    break;
                }


                case 2 -> {
                    System.out.println("Enter the username to log in");
                    String nameToLogin = sc.next();
                    System.out.println("Enter the password to log in");
                    String passwordToLogin = sc.next();

                    User userToLogin = new User(nameToLogin, UUID.randomUUID().toString(), passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin),
                            new ArrayList<>());

                    try {
                        userBookingService = new UserBookingService(userToLogin);
                    } catch (IOException exception) {
                        return;
                    }
                    break;
                }

                case 3 -> {
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                }

                case 4 -> {
                    System.out.println("Type your source station");
                    String source = sc.next();
                    System.out.println("Type your destination station");
                    String destination = sc.next();

                    List<Train> trains = userBookingService.getTrains(source, destination);

                    int index = 1;
                    for (Train t: trains) {
                        System.out.println(index + " Train id: " + t.getTrainId());
                        for (Map.Entry<String, String> entry: t.getStationTimes().entrySet()) {
                            System.out.println("station " + entry.getKey() + " time: " + entry.getValue());
                        }
                    }

                    System.out.println("Select a train(1, 2, 3, ..): ");
                    trainsSelectedForBooking = trains.get(sc.nextInt());
                    break;
                }

                case 5 -> {
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainsSelectedForBooking);
                    for (List<Integer> row: seats) {
                        for (Integer val: row) {
                            System.out.print(val + " ");
                        }
                        System.out.println();
                    }

                    System.out.println("Select the seat by typing row and column");
                    System.out.println("Enter the row");
                    int row = sc.nextInt();
                    System.out.println("Enter the column");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat...");
                    Boolean booked = userBookingService.bookTrainSeat(trainsSelectedForBooking, row, col);
                    if (booked.equals(Boolean.TRUE)) {
                        System.out.println("Booked enjoy your journey!");
                    } else {
                        System.out.println("Cannot book this seat");
                    }
                    break;
                }
                default -> {
                    break;
                }

            }
        }

    }

    public String  getGreeting() {
        return "HEllo";
    }
}
